# check_leaks.mcfunction - Autogenerated
scoreboard players set #breached sd_score 0

# Check physical sandbag placement in the 5 perimeter gaps
execute unless block 612 -48 545 minecraft:yellow_concrete run scoreboard players set #breached sd_score 1
execute unless block 604 -48 552 minecraft:yellow_concrete run scoreboard players set #breached sd_score 1
execute unless block 603 -48 559 minecraft:yellow_concrete run scoreboard players set #breached sd_score 1
execute unless block 614 -48 568 minecraft:yellow_concrete run scoreboard players set #breached sd_score 1
execute unless block 620 -48 555 minecraft:yellow_concrete run scoreboard players set #breached sd_score 1

# Check for water breaches inside the house floor (Y=-48)
execute if block 612 -48 558 minecraft:water run scoreboard players set #breached sd_score 1
execute if block 610 -48 556 minecraft:water run scoreboard players set #breached sd_score 1
execute if block 614 -48 560 minecraft:water run scoreboard players set #breached sd_score 1
execute if block 615 -48 553 minecraft:water run scoreboard players set #breached sd_score 1
execute if block 608 -48 562 minecraft:water run scoreboard players set #breached sd_score 1

# Trigger failure if breached
execute if score #breached sd_score matches 1.. run tellraw @a [{"text":"[Sandbag Defense] ","color":"red"},{"text":"Water leaked through the sandbag perimeter!","color":"yellow"}]
execute if score #breached sd_score matches 1.. run function sandbag_defense:fail

# Trigger win if NO breach
execute if score #breached sd_score matches 0 run function sandbag_defense:win