# spawn_water.mcfunction - Autogenerated
# Spreads naturally to check physical sandbag barrier integrity

# Layer 1 (Street level / Y = -49): Spawns at 15s remaining (300 ticks)
execute if score #time sd_timer matches ..300 run fill 601 -49 541 601 -49 571 minecraft:water replace air
execute if score #time sd_timer matches ..300 run fill 623 -49 541 623 -49 571 minecraft:water replace air
execute if score #time sd_timer matches ..300 run fill 601 -49 541 623 -49 541 minecraft:water replace air
execute if score #time sd_timer matches ..300 run fill 601 -49 571 623 -49 571 minecraft:water replace air

# Layer 2 (1 block deep / Y = -48): Spawns at 10s remaining (200 ticks)
execute if score #time sd_timer matches ..200 run fill 601 -48 541 601 -48 571 minecraft:water replace air
execute if score #time sd_timer matches ..200 run fill 623 -48 541 623 -48 571 minecraft:water replace air
execute if score #time sd_timer matches ..200 run fill 601 -48 541 623 -48 541 minecraft:water replace air
execute if score #time sd_timer matches ..200 run fill 601 -48 571 623 -48 571 minecraft:water replace air
