# check_leaks.mcfunction - Autogenerated
scoreboard players set #breached sd_score 0

execute if block 613 -49 545 minecraft:water run scoreboard players set #breached sd_score 1
execute if block 605 -49 552 minecraft:water run scoreboard players set #breached sd_score 1
execute if block 604 -49 559 minecraft:water run scoreboard players set #breached sd_score 1
execute if block 614 -49 567 minecraft:water run scoreboard players set #breached sd_score 1
execute if block 620 -49 554 minecraft:water run scoreboard players set #breached sd_score 1

# Trigger failure if breached
execute if score #breached sd_score matches 1.. run tellraw @a [{"text":"[Sandbag Defense] ","color":"red"},{"text":"Water leaked through the sandbag perimeter!","color":"yellow"}]
execute if score #breached sd_score matches 1.. run function sandbag_defense:fail

# Trigger win if NO breach
execute if score #breached sd_score matches 0 run function sandbag_defense:win