# reset.mcfunction - Autogenerated
scoreboard players set @a sd_deaths 0
clear @a
gamemode creative @a
bossbar set minecraft:sd_bossbar visible false

# 1. Clear all water FIRST
fill 600 -49 540 624 -45 572 minecraft:air replace minecraft:water

# 2. Clear sandbag wall
fill 600 -49 540 624 -45 572 minecraft:air replace minecraft:yellow_concrete

# 3. Clear containment barriers
fill 600 -49 540 624 -45 572 minecraft:air replace minecraft:structure_void
