# start.mcfunction - Autogenerated
function sandbag_defense:reset
scoreboard players add #game_id sd_game 1
scoreboard players set #state sd_state 1
scoreboard players set #time sd_timer 700
scoreboard players set @a sd_deaths 0
clear @a
gamemode adventure @a
item replace entity @a hotbar.0 with written_book[written_book_content={title:"Defense Plan",author:"City Engineer",pages:['{"text":"Sandbag Defense:\\n\\nUh oh! The crew missed\\na few spots!\\n\\nTake the sandbags in\\nyour inventory and\\nrun around the house\\nto plug the 5 gaps\\nbefore the flood hits!\\n\\n(Flip page ->)"}','{"text":"Did you know?\\n\\nSandbags are cheap and\\neasy to deploy but\\nonly work for shallow\\nflooding.\\n\\nThey must form a\\ncontinuous line to\\nkeep the water out!"}']}] 1
item replace entity @a hotbar.1 with minecraft:yellow_concrete[minecraft:can_place_on={blocks:["minecraft:stone_bricks","minecraft:mossy_stone_bricks","minecraft:cracked_stone_bricks","minecraft:chiseled_stone_bricks","minecraft:stone","minecraft:grass_block","minecraft:dirt","minecraft:short_grass","minecraft:tall_grass","minecraft:gray_concrete"]}] 10
tp @a 613 -48 545 180 0
bossbar set minecraft:sd_bossbar visible true
bossbar set minecraft:sd_bossbar players @a
bossbar set minecraft:sd_bossbar max 700
bossbar set minecraft:sd_bossbar value 700
title @a times 10 60 10
title @a title {"text":"MISSING SANDBAGS!","color":"red"}
title @a subtitle {"text":"Fill the 5 gaps before the flood starts!","color":"yellow"}
tellraw @a [{"text":"[Sandbag Defense] ","color":"gold"},{"text":"The crew missed a few spots! Find the 5 gaps in the perimeter and fill them before the timer runs out!","color":"yellow"}]
playsound minecraft:entity.elder_guardian.curse master @a ~ ~ ~ 1 1

# Place sandbag wall
setblock 603 -48 556 minecraft:yellow_concrete replace
setblock 603 -48 557 minecraft:yellow_concrete replace
setblock 603 -48 558 minecraft:yellow_concrete replace
setblock 603 -48 560 minecraft:yellow_concrete replace
setblock 603 -48 561 minecraft:yellow_concrete replace
setblock 603 -48 562 minecraft:yellow_concrete replace
setblock 603 -48 563 minecraft:yellow_concrete replace
setblock 604 -48 550 minecraft:yellow_concrete replace
setblock 604 -48 551 minecraft:yellow_concrete replace
setblock 604 -48 553 minecraft:yellow_concrete replace
setblock 604 -48 554 minecraft:yellow_concrete replace
setblock 604 -48 555 minecraft:yellow_concrete replace
setblock 604 -48 556 minecraft:yellow_concrete replace
setblock 604 -48 563 minecraft:yellow_concrete replace
setblock 605 -48 548 minecraft:yellow_concrete replace
setblock 605 -48 549 minecraft:yellow_concrete replace
setblock 605 -48 550 minecraft:yellow_concrete replace
setblock 605 -48 563 minecraft:yellow_concrete replace
setblock 605 -48 564 minecraft:yellow_concrete replace
setblock 606 -48 547 minecraft:yellow_concrete replace
setblock 606 -48 548 minecraft:yellow_concrete replace
setblock 606 -48 564 minecraft:yellow_concrete replace
setblock 607 -48 545 minecraft:yellow_concrete replace
setblock 607 -48 546 minecraft:yellow_concrete replace
setblock 607 -48 547 minecraft:yellow_concrete replace
setblock 607 -48 564 minecraft:yellow_concrete replace
setblock 607 -48 565 minecraft:yellow_concrete replace
setblock 608 -48 545 minecraft:yellow_concrete replace
setblock 608 -48 565 minecraft:yellow_concrete replace
setblock 608 -48 566 minecraft:yellow_concrete replace
setblock 609 -48 545 minecraft:yellow_concrete replace
setblock 609 -48 566 minecraft:yellow_concrete replace
setblock 609 -48 567 minecraft:yellow_concrete replace
setblock 610 -48 545 minecraft:yellow_concrete replace
setblock 610 -48 567 minecraft:yellow_concrete replace
setblock 611 -48 545 minecraft:yellow_concrete replace
setblock 611 -48 567 minecraft:yellow_concrete replace
setblock 612 -48 567 minecraft:yellow_concrete replace
setblock 612 -48 568 minecraft:yellow_concrete replace
setblock 613 -48 545 minecraft:yellow_concrete replace
setblock 613 -48 568 minecraft:yellow_concrete replace
setblock 614 -48 545 minecraft:yellow_concrete replace
setblock 614 -48 546 minecraft:yellow_concrete replace
setblock 615 -48 546 minecraft:yellow_concrete replace
setblock 615 -48 547 minecraft:yellow_concrete replace
setblock 615 -48 568 minecraft:yellow_concrete replace
setblock 616 -48 547 minecraft:yellow_concrete replace
setblock 616 -48 567 minecraft:yellow_concrete replace
setblock 616 -48 568 minecraft:yellow_concrete replace
setblock 617 -48 547 minecraft:yellow_concrete replace
setblock 617 -48 548 minecraft:yellow_concrete replace
setblock 617 -48 565 minecraft:yellow_concrete replace
setblock 617 -48 566 minecraft:yellow_concrete replace
setblock 617 -48 567 minecraft:yellow_concrete replace
setblock 618 -48 548 minecraft:yellow_concrete replace
setblock 618 -48 562 minecraft:yellow_concrete replace
setblock 618 -48 563 minecraft:yellow_concrete replace
setblock 618 -48 564 minecraft:yellow_concrete replace
setblock 618 -48 565 minecraft:yellow_concrete replace
setblock 619 -48 548 minecraft:yellow_concrete replace
setblock 619 -48 549 minecraft:yellow_concrete replace
setblock 619 -48 558 minecraft:yellow_concrete replace
setblock 619 -48 559 minecraft:yellow_concrete replace
setblock 619 -48 560 minecraft:yellow_concrete replace
setblock 619 -48 561 minecraft:yellow_concrete replace
setblock 619 -48 562 minecraft:yellow_concrete replace
setblock 620 -48 549 minecraft:yellow_concrete replace
setblock 620 -48 550 minecraft:yellow_concrete replace
setblock 620 -48 551 minecraft:yellow_concrete replace
setblock 620 -48 552 minecraft:yellow_concrete replace
setblock 620 -48 553 minecraft:yellow_concrete replace
setblock 620 -48 554 minecraft:yellow_concrete replace
setblock 620 -48 556 minecraft:yellow_concrete replace
setblock 620 -48 557 minecraft:yellow_concrete replace
setblock 620 -48 558 minecraft:yellow_concrete replace
setblock 638 -48 534 minecraft:yellow_concrete replace
setblock 640 -48 536 minecraft:yellow_concrete replace

# Place invisible containment barriers (Outer bounds)

fill 600 -49 540 600 -48 572 minecraft:structure_void replace minecraft:air
fill 624 -49 540 624 -48 572 minecraft:structure_void replace minecraft:air
fill 600 -49 540 624 -48 540 minecraft:structure_void replace minecraft:air
fill 600 -49 572 624 -48 572 minecraft:structure_void replace minecraft:air
